name: Sync Pull Request to Azure Boards

on:
  pull_request_target:
    types: [opened, edited, closed]
    branches:
      - main
      - Caso-de-Uso
      

jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
    - uses: danhellem/github-actions-pr-to-work-item@master
      env:
        ado_token: '${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}'   
        github_token: '${{ secrets.GH_TOKEN }}'    
        ado_organization: 'romulocesarteste1'
        ado_project: '2020.1191.005-BARBER%20TIP'
        ado_wit: 'Task' 
        ado_new_state: 'To Do'
        ado_active_state: 'In Progress'
        ado_close_state: 'Done'
        ado_area_path: 'optional_area_path\\optional_area_path'
